server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(jpg|jpeg|png|gif|ico|svg|webp|mp4|mov)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    location ~* \.(css|js)$ {
        expires 1d;
        add_header Cache-Control "public";
    }
}
